In [17]:
with open(r, 'r',encoding='utf-8') as f:
    text = f.read()
print(text[:200])

 DOROTHY AND THE WIZARD IN OZ

 BY

 L. FRANK BAUM

 AUTHOR OF THE WIZARD OF OZ, THE LAND OF OZ, OZMA OF OZ, ETC.

 ILLUSTRATED BY JOHN R. NEILL

 BOOKS OF WONDER WILLIAM MORROW & CO., INC. NEW YORK



In [ ]:
import torch

device= 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

with open(r'C:\Users\user\PycharmProjects\pythonProject\Luckyprojects\AIprojects\AI3model\gpt-course\wizards_of_oz.txt',
          'r', encoding='utf-8') as f:
    text = f.read()
chars = sorted(set(text))

vocabulary_size = len(chars)

string_to_int = {ch: i for i, ch in enumerate(chars)}
int_to_string = {i: ch for i, ch in enumerate(chars)}
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

data = torch.tensor(encode(text), dtype=torch.long)

n = int(0.8 * len(data))
train_data = data[:n]
val_data = data[n:]

block_size = 8

x = train_data[:block_size]
y = train_data[1:block_size + 1]

for t in range(block_size):
    context = x[:t + 1]
    target = y[t]
    print('when input is ', context, 'target is ', target)


In [2]:
print("boo")

boo


In [4]:
import torch


block_size=8
batch_size=4


with open(r'C:\Users\user\PycharmProjects\pythonProject\Luckyprojects\AIprojects\AI3model\gpt-course\wizards_of_oz.txt',
          'r', encoding='utf-8') as f:
    text = f.read()
chars = sorted(set(text))

vocabulary_size = len(chars)

string_to_int = {ch: i for i, ch in enumerate(chars)}
int_to_string = {i: ch for i, ch in enumerate(chars)}
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

data = torch.tensor(encode(text), dtype=torch.long)

n = int(0.8 * len(data))
train_data = data[:n]
val_data = data[n:]

x = train_data[:block_size]
y = train_data[1:block_size + 1]

for t in range(block_size):
    context = x[:t + 1]
    target = y[t]
    print('when input is ', context, 'target is ', target)


when input is  tensor([80]) target is  tensor(1)
when input is  tensor([80,  1]) target is  tensor(28)
when input is  tensor([80,  1, 28]) target is  tensor(39)
when input is  tensor([80,  1, 28, 39]) target is  tensor(42)
when input is  tensor([80,  1, 28, 39, 42]) target is  tensor(39)
when input is  tensor([80,  1, 28, 39, 42, 39]) target is  tensor(44)
when input is  tensor([80,  1, 28, 39, 42, 39, 44]) target is  tensor(32)
when input is  tensor([80,  1, 28, 39, 42, 39, 44, 32]) target is  tensor(49)


In [5]:
import torch

randint = torch.randint(-100,100,(6,))
randint

tensor([-65, -45,  23, -70, -84,  67])

In [12]:
tensor = torch.tensor([[0.1,1.2],[2.2,3.1],[4.9,5.2]])
tensor


tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [16]:
zeros=torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [18]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
input = torch.empty(2, 3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [22]:
input = torch.empty(2, 3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [3]:
arange = torch.arange(5)
arange

NameError: name 'torch' is not defined

In [28]:
linespace = torch.linspace(3,10,steps=5)
linespace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [9]:
logspace = torch.logspace(-10,10, stes=5)
logspace

TypeError: logspace() received an invalid combination of arguments - got (int, int, stes=int), but expected one of:
 * (Tensor start, Tensor end, int steps, float base, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Number start, Tensor end, int steps, float base, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Tensor start, Number end, int steps, float base, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Number start, Number end, int steps, float base, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


In [3]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

print("the total number of characters:", len(raw_text))
print(raw_text[:100])

FileNotFoundError: [Errno 2] No such file or directory: 'the-verdict.txt'

In [5]:
with open(r"C:\Users\user\PycharmProjects\pythonProject\Luckyprojects\AIprojects\LLM\the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

print("the total number of characters:", len(raw_text))
print(raw_text[:100])

the total number of characters: 0



In [19]:
with open(r"C:\Users\user\PycharmProjects\pythonProject\Luckyprojects\AIprojects\LLM\the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

total_characters = len(raw_text)

print("The total number of characters:", total_characters)

print(raw_text[:100])

The total number of characters: 20479
I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no g
